name: Creating Environments Test

on: workflow_dispatch

jobs: 
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Development, Production]
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ matrix.environment }}
          echo ${{ secrets.API_KEY }}
      - uses: ./.github/workflows/matrix.yml@main