name: Matrix Tests

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet:  [Cat, Dog]
        color: [White, Black]
        include:
          - pet:  Bird
            color: Blue
    steps:
      - run: echo "The ${{ matrix.pet }} is ${{ matrix.color }}"