name: Test 2 Inputs

on:
  workflow_dispatch:
    inputs:
      stage:
        type: string
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Stage
        id: stage
        run: echo "STAGE_BUILD=${{ inputs.stage }}" >> $GITHUB_OUTPUT
      - name: Get Stage FROM stage step
        run: echo "The stage is ${{ steps.stage.outputs.STAGE_BUILD }}"